# Generated by Django 5.2.1 on 2025-05-28 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('ano_modelo', models.IntegerField(blank=True, null=True, verbose_name='Ano do Modelo')),
                ('placa', models.CharField(help_text='Formato AAA-9999 ou ABC1D23', max_length=8, unique=True, verbose_name='Placa')),
                ('chassi', models.CharField(max_length=17, unique=True, verbose_name='Chassi')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('preco_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Compra')),
                ('preco_venda_sugerido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda Sugerido')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada no Estoque')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_negociacao', 'Em Negociação'), ('vendido', 'Vendido')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['-data_entrada', 'marca', 'modelo'],
            },
        ),
    ]
